[web]
web_node ansible_host=127.0.0.1 ansible_port=2221

[db]
db_node ansible_host=127.0.0.1 ansible_port=2222

[all:vars]
ansible_user=root
ansible_password=root
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

